USE UNIVERSITY

SELECT DISTINCT PULPIT.PULPIT_NAME
FROM FACULTY INNER JOIN PULPIT
ON FACULTY.FACULTY = PULPIT.FACULTY
WHERE FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY FROM PROFESSION
WHERE PROFESSION.PROFESSION_NAME LIKE '%технологи%')

USE N_MyBASE

SELECT Departments.Department_Name
FROM Expenses INNER JOIN Departments
ON Expenses.Department_Name = Departments.Department_Name
WHERE Expenses.Product_Name IN (SELECT Products.Product_Name FROM Products
WHERE Products.Product_Name LIKE '%RTX%')