USE UNIVERSITY

SELECT DISTINCT PULPIT.PULPIT_NAME
FROM FACULTY 
INNER JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
INNER JOIN PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
WHERE PROFESSION.PROFESSION_NAME LIKE '%технологи%'

USE N_MyBASE

SELECT Departments.Department_Name
FROM Expenses 
INNER JOIN Departments ON Expenses.Department_Name = Departments.Department_Name
INNER JOIN Products ON Expenses.Product_Name = Products.Product_Name
WHERE Products.Product_Name LIKE '%RTX%'
