USE UNIVERSITY

SELECT TOP(1)
(SELECT AVG(NOTE) FROM PROGRESS
	WHERE SUBJECT LIKE '%нюХо%')[нюХо],
(SELECT AVG(NOTE) FROM PROGRESS
	WHERE SUBJECT LIKE '%ад%')[ад],
(SELECT AVG(NOTE) FROM PROGRESS
	WHERE SUBJECT LIKE '%ясад%')[ясад]
FROM PROGRESS

USE N_MyBASE

SELECT TOP(1)
(SELECT AVG(Consuption_Limit) FROM Expenses
	WHERE Department_Name LIKE '%2')[DEV_2],
(SELECT AVG(Consuption_Limit) FROM Expenses
	WHERE Department_Name LIKE '%5')[DEV_5]
FROM Expenses