USE UNIVERSITY

SELECT FACULTY_NAME 
FROM FACULTY
WHERE EXISTS (SELECT* FROM PULPIT WHERE PULPIT.FACULTY = FACULTY.FACULTY)

USE N_MyBASE

SELECT Product_Name
FROM Products
WHERE EXISTS (SELECT * FROM Expenses WHERE Expenses.Product_Name = Products.Product_Name)