USE UNIVERSITY

SELECT DISTINCT PULPIT.PULPIT_NAME
FROM FACULTY, PULPIT, PROFESSION
WHERE FACULTY.FACULTY = PULPIT.FACULTY
AND FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY FROM PROFESSION
WHERE PROFESSION.PROFESSION_NAME LIKE '%технологи%')

USE N_MyBASE

SELECT Departments.Department_Name
FROM Expenses, Departments
WHERE Expenses.Department_Name = Departments.Department_Name
AND Expenses.Product_Name IN (SELECT Products.Product_Name FROM Products
WHERE Products.Product_Name LIKE '%RTX%')

