USE UNIVERSITY

BEGIN TRY
UPDATE STUDENT SET IDGROUP = 'string' WHERE IDGROUP = 18
END TRY
BEGIN CATCH
PRINT 'ERROR_NUMBER:	' + CAST(ERROR_NUMBER() AS CHAR)
PRINT 'ERROR_MESSAGE:	' + ERROR_MESSAGE()
PRINT 'ERROR_LINE:		' + CAST(ERROR_LINE() AS CHAR)
PRINT 'ERROR_PROCEDURE:	' + ERROR_PROCEDURE()
PRINT 'ERROR_SEVERITY:	' + CAST(ERROR_SEVERITY() AS CHAR)
PRINT 'ERROR_STATE:		' + CAST(ERROR_STATE() AS CHAR)
END CATCH