use UNIVERSITY

--SELECT * FROM PROGRESS SELECT* FROM STUDENT SELECT * FROM GROUPS SELECT* FROM SUBJECT SELECT* FROM PULPIT SELECT* FROM FACULTY

SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT, GROUPS.FACULTY, SUBJECT.SUBJECT_NAME,
STUDENT.NAME,
CASE
WHEN(PROGRESS.NOTE = 6) THEN 'шесть'
WHEN(PROGRESS.NOTE = 7) THEN 'семь'
WHEN(PROGRESS.NOTE = 8) THEN 'восем'
END[MARK]
FROM FACULTY
inner join PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
inner join SUBJECT ON PULPIT.PULPIT = SUBJECT.PULPIT
inner join PROGRESS ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
inner join STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP

WHERE PROGRESS.NOTE BETWEEN 6 and 8

ORDER BY PROGRESS.NOTE DESC

use N_MyBASE 

--SELECT* FROM  Departments SELECT* FROM Expenses SELECT* FROM Products

SELECT Departments.Department_Name, Expenses.Product_Name,
Products.Description_About_Product,
CASE
WHEN(Expenses.Consuption_Limit > 900) THEN 'Лимит превышен'
WHEN(Expenses.Consuption_Limit < 900) THEN 'Ok'
END[LIMIT]
FRoM Departments
inner join Expenses ON Departments.Department_Name = Expenses.Department_Name
inner join Products ON Expenses.Product_Name = Products.Product_Name

